import "./globals.css";
import { Inter } from "next/font/google";
import UniversityProvider from "@/providers/university-provider";

const inter = Inter({ subsets: ["latin"] });
import { ThemeProvider } from "@/providers/theme-provider";
import { Header } from "../components/Header";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UniversityProvider>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            <header className="flex min-h-screen w-full flex-col p-4">
              <Header />
              {children}
            </header>
          </ThemeProvider>
        </UniversityProvider>
      </body>
    </html>
  );
}
